name: Entrega Contínua

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-20.04  # Ambiente atualizado

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go 1.18  # Definindo a versão correta do Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run tests
      run: go test ./... # Comando de teste do Go

  EC2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: programa

    - name: Deploy to Staging Server via SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
      with:
        source: ./  # Diretório local
        target: /home/${{ secrets.REMOTE_USER }}/deploy/  # Diretório remoto
